#!/bin/ksh

set -e
set -o noglob

PROG=${0##*/}
if [[ "$0" = */* ]]; then
    ORIGIN=${0%/*}
    if [[ "$ORIGIN" != /* ]]; then
        ORIGIN=${PWD}/$ORIGIN
    fi
else
    ORIGIN=${PWD}
fi
XSL=$ORIGIN/lyxhtml2xml2rfc.xsl

LYX_XHTML_DTD=http://www.w3.org/TR/MathML2/dtd/xhtml-math11-f.dtd
XHTML_DTD=http://www.w3.org/TR/2001/REC-MathML2-20010221/dtd/xhtml-math11-f.dtd
LOCAL_XHTML_DTD=$ORIGIN/xhtml-math11-f.dtd

function usage {
    printf "Usage: $PROG lyx_file [out_file]\n"
    exit 1
}

# Very, very lame command-line parsing (should use getopts).
#
# The first argument must be a LyX document filename.  If it doesn't end
# in .lyx we'll tack on the .lyx extension.
#
# The second argument must be an output filename.  The extension must be
# one of txt, pdf, html, or xml.  If no extension is provided we'll tack
# on '.txt'.
(($# > 0)) || usage
(($# < 3)) || usage
lyxf=$1
[[ "$lyxf" != *.lyx && "$lyxf" != *.* ]] && lyxf=${lyxf}.lyx
[[ "$lyxf" != *.lyx ]] && usage
xhtml=${1:%.lyx}.xhtml
out=${2:-${lyxf%.lyx}.txt}
[[ "$out" != *.* ]] && out=${out}.txt
[[ "$out" != *.@(txt|pdf|html|xml) ]] && usage
xmlout=${out%.@(txt|pdf|html|xml)}.xml

# Get and cache a local copy of the XHTML DTD:
if [[ ! -f "$LOCAL_XHTML_DTD" ]]; then
    wget $XHTML_DTD
fi

# Export LyX document as XHTML:
printf "Exporting LyX document as XHTML...\n"
lyx -e xhtml "$lyxf"

# Fix DTD URL in XHTML to refer to the local copy (LyX uses a dead URL):
sed --in-place -e "s,${LYX_XHTML_DTD},file://${LOCAL_XHTML_DTD}," "$xhtml"

# Apply the lyx2rfc XSTL stylesheet and pretty-print result:
# (the old xml2rfc tool doesn't grok xmlns attributes; remove them)
printf "Applying XSLT stylesheet for XHTML->rfc2629.dtd conversion...\n"
java net/sf/saxon/Transform "$xhtml" $XSL | 
    sed -e 's,xmlns="xml2rfc",,' -e 's/></>\n</g' |
    xmllint --format - > "$xmlout"

# Set the correct DTD URL, just so we don't have a local path left here
sed --in-place -e "s,file://${LOCAL_XHTML_DTD},${XHTML_DTD}," "$xhtml"


# Run xml2rfc to do the final conversion if desired:
printf "Applying xml2rfc for final formatting...\n"
[[ "$out" != *.xml ]] && DISPLAY= xml2rfc "$xmlout" "$out"

